# Week 1 in class

This is one of the notebooks that we work on together in class. In this way you can work on tougher problems, on your own or with a small group of other students, and have plenty of time to ask questions about things that you do not understand. 

If you do not manage to finish the notebook in class, then finish it yourself at home. The notebook is written in such a way that you can go through it on your own. If you do run into problems, ask us on the discussion forum, in the Q&A session, or next week.

#### Learning goals
- Extending your knowlegde of object types to *tuples*.
- Introducing you to an important application of strings: *string formatting*.
- Increasing your comfort with `numpy`, with an application to financial arithmetic.

## Tuples
<a id='3'></a>

Tuples are very similar to lists and hold ordered collections of items.

However, tuples and lists have three main differences:

1. Tuples are created using parenthesis — `(` and `)` — instead of
  square brackets — `[` and `]`.  
1. Tuples are *immutable*, which is a fancy computer science word
  meaning that they can’t be changed or altered after they are created.  
1. Tuples and multiple return values
  from functions are tightly connected, as we will see in functions.  

In [1]:
t = (1, "hello", 3.0)
print("t is a", type(t))
t

t is a <class 'tuple'>


(1, 'hello', 3.0)

We can *convert* a list to a tuple by calling the `tuple` function on
a list.

In [2]:
x = [1,2]
print("x is a", type(x))
print("tuple(x) is a", type(tuple(x)))
tuple(x)

x is a <class 'list'>
tuple(x) is a <class 'tuple'>


(1, 2)

We can also convert a tuple to a list using the list function.

In [3]:
list(t)

[1, 'hello', 3.0]

### List vs Tuple: Which to Use?

Should you use a list or tuple?

This depends on what you are storing, whether you might need to reorder the elements,
or whether you’d add
new elements without a complete reinterpretation of the
underlying data.

For example, take data representing the GDP (in trillions) and population
(in billions) for China in 2015.

In [4]:
china_data_2015 = ("China", 2015, 11.06, 1.371)

print(china_data_2015)

('China', 2015, 11.06, 1.371)


In this case, we have used a tuple since: (a) ordering would
be meaningless; and (b) adding more data would require a
reinterpretation of the whole data structure.

On the other hand, consider a list of GDP in China between
2014 and 2015.

In [5]:
gdp_data = [10.48, 11.06]
print(gdp_data)

[10.48, 11.06]


In this case, we have used a list, since adding on a new
element to the end of the list for GDP in 2016 would make
complete sense.

Along these lines, collecting data on China for different
years may make sense as a list of tuples (e.g. year, GDP,
and population – although we will see better ways to store this sort of data
when we learn Pandas

In [42]:
china_data = [(2015, 11.06, 1.371), (2014, 10.48, 1.364)]
print(china_data)

[(2015, 11.06, 1.371), (2014, 10.48, 1.364)]


#### Exercise 1

Verify that tuples are indeed immutable and lists are not, by attempting the following:

- Changing the GDP in 2015 to 12.00
- Appending observations for 2013: a GDP of 9.607, and a population of 1.357
- Sorting the data ascending in years

In [43]:
# YOUR CODE HERE
#raise NotImplementedError()
#china_data_2015[2] = '12.00'
x = (2013, 9.607, 1.357)
china_data.append(x)
sorted_china = sorted(china_data)
print(sorted_china)


[(2013, 9.607, 1.357), (2014, 10.48, 1.364), (2015, 11.06, 1.371)]


### Conclusion

In general, a rule of thumb is to use a list unless you *need* to use a tuple.

Key criteria for tuple use are when you want to:

- ensure the *order* of elements can’t change  
- ensure the actual values of the elements can’t
  change  
- use the collection as a key in a dictionary (we will learn what this
  means next week)  

## String Formatting
<a id='1'></a>
Sometimes we’d like to reuse some portion of a string repeatedly, but
still make some relatively small changes at each usage.

We can do this with *string formatting*, which done by using `{}` as a
*placeholder* where we’d like to change the string, with a variable name
or expression.

Let’s look at an example.

In [35]:
country = "Vietnam"
GDP = 223.9
year = 2017
my_string = f"{country} had ${GDP} billion GDP in {year}"
print(my_string)

Vietnam had $223.9 billion GDP in 2017


Rather than just substituting a variable name, you can use a calculation
or expression.

In [44]:
print(f"{5}**2 = {5**2}")

5**2 = 25


Or, using our previous example

In [45]:
my_string = f"{country} had ${GDP * 1_000_000} GDP in {year}"
print(my_string)

Vietnam had $223900000.0 GDP in 2017


In these cases, the `f` in front of the string causes Python interpolate
any valid expression within the `{}` braces.

Alternatively, to reuse a formatted string, you can call the `format` *method* (noting that you do **not** put `f` in front).

In [46]:
gdp_string = "{country} had ${GDP} billion in {year}"

gdp_string.format(country = "Vietnam", GDP = 223.9, year = 2017)

'Vietnam had $223.9 billion in 2017'

#### Exercise 2

Lookup a country in [World Bank database](https://data.worldbank.org/), and format a string showing the growth rate of GDP over the last 2 years.

Note, incidently how we created a link in markdown in the previous sentence. Double click on this cell, to see the syntax for a link in markdown.

In [59]:
# YOUR CODE HERE
#raise NotImplementedError()
GDP_2019 = 31.046
GDP_2018 = 30.475
year = 2019
Country = "Estonia"

Now, instead of hard-coding the values above, try using `format` function by defining country, GDP and year as variables.

In [60]:
# YOUR CODE HERE
#raise NotImplementedError()
true_string = f"The GDP Growth rate of {Country} in {year} was {(GDP_2019-GDP_2018)/GDP_2019 * 100}%"
print(true_string)

The GDP Growth rate of Estonia in 2019 was 1.8392063389808606%


#### Exercise 3

Create a new string and use formatting to produce each of the following statements:
- "The 1st quarter revenue was 110M"
- "The 2nd quarter revenue was 95M"
- "The 3rd quarter revenue was 100M"
- "The 4th quarter revenue was 130M"

In [85]:
# YOUR CODE HERE
#raise NotImplementedError()
Quarter = ["1st", "2nd", "3rd", "4th"]  # () - tuple, [] - list
rev = [110, 95,100,130]
for i in range(len(rev)):
    
    ducks =f"The {Quarter[i]} quarter revenue was {rev[i]}M"
    print(ducks)



The 1st quarter revenue was 110M
The 2nd quarter revenue was 95M
The 3rd quarter revenue was 100M
The 4th quarter revenue was 130M


## Numpy

Numpy’s core contribution is a data-type called an array. An array is similar to a list, but numpy imposes some additional restrictions on how the data inside is organized.

These restrictions allow numpy to

1. Be more efficient in performing mathematical and scientific computations.
2. Expose functions that allow numpy to do the necessary linear algebra for machine learning and statistics.

Before we get started, please note that the convention for importing the numpy package is to use the nickname np:

In [86]:
import numpy as np

### Array Indexing

An array is a multi-dimensional grid of values. Now that there are multiple dimensions, indexing might feel somewhat non-obvious. Do the rows or columns come first? In higher dimensions, what is the order of
the index?

Notice that the array is built using a list of lists. Indexing into the array will correspond to choosing elements from each list.

First, notice that a 3-dimensional array give two stacked matrices:

In [87]:
x_3d_list = [[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
x_3d = np.array(x_3d_list)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


We can access the matrices with

In [88]:
print(x_3d[0])
print(x_3d[1])

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In the case of the first, it is synonymous with

In [92]:
print(x_3d[0, :, :])

[[1 2 3]
 [4 5 6]]


Let’s work through another example to further clarify this concept with our
3-dimensional array.

Our goal will be to find the index that retrieves the `4` out of `x_3d`.

Recall that when we created `x_3d`, we used the list `[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]`.

Notice that the 0 element of that list is `[[1, 2, 3], [4, 5, 6]]`. This is the
list that contains the `4` so the first index we would use is a 0.

In [177]:
print(x_3d[0, 1, 0])


4


**Exercise 4**

What would you do to extract the array `[[5, 6], [50, 60]]` from `x_3d`?

In [94]:
# YOUR CODE HERE
#raise NotImplementedError()
print(x_3d[:,1,1:3])

[[ 5  6]
 [50 60]]


### Array Functionality

#### Creating Arrays

It’s usually impractical to define arrays by hand as we have done so far.

We’ll often need to create an array with default values and then fill it
with other values.

We can create arrays with the functions `np.zeros` and `np.ones`.

Both functions take a tuple that denotes the shape of an array and creates an
array filled with 0s or 1s respectively.

In [95]:
sizes = (2, 3, 4)
x = np.zeros(sizes) # note, a tuple!
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [96]:
y = np.ones((4))
y

array([1., 1., 1., 1.])

#### Broadcasting Operations

Two types of operations that will be useful for arrays of any dimension are:

1. Operations between an array and a single number.  
1. Operations between two arrays of the same shape.  


When we perform operations on an array by using a single number, we simply apply that operation to every element of the array.

In [97]:
# Using np.ones to create an array
x = np.ones((2, 2))
print("x = ", x)
print("2 + x = ", 2 + x)
print("2 - x = ", 2 - x)
print("2 * x = ", 2 * x)
print("x / 2 = ", x / 2)

x =  [[1. 1.]
 [1. 1.]]
2 + x =  [[3. 3.]
 [3. 3.]]
2 - x =  [[1. 1.]
 [1. 1.]]
2 * x =  [[2. 2.]
 [2. 2.]]
x / 2 =  [[0.5 0.5]
 [0.5 0.5]]


Operations between two arrays of the same size, in this case `(2, 2)`, simply apply the operation element-wise between the arrays.

In [104]:
x = np.array([[1.0, 2.0], [3.0, 4.0]])
y = np.ones((2, 2))
print("x = ", x)
print("y = ", y)
print("x + y = ", x + y)
print("x - y = ", x - y)
print("(elementwise) x * y = ", x * y)
print("(elementwise) x / y = ", x / y)
result = np.array([1, 2, 3]) + [4]
print(result)

x =  [[1. 2.]
 [3. 4.]]
y =  [[1. 1.]
 [1. 1.]]
x + y =  [[2. 3.]
 [4. 5.]]
x - y =  [[0. 1.]
 [2. 3.]]
(elementwise) x * y =  [[1. 2.]
 [3. 4.]]
(elementwise) x / y =  [[1. 2.]
 [3. 4.]]
[5 6 7]


**Exercise 5**

Consider the code `[1, 2, 3] + [4]`. What is the difference between the output of this code and the output of `np.array([1, 2, 3]) + [4]`?

First code adds 4 to the list of [1,2,3]. 
Second code makes a matrix 1x3 with values [1,2,3] and adds 4 to each element - creating a matrix [5,6,7]


**Exercise 6**

Do you recall what multiplication by an integer did for lists?

How does broadcasting differ?

Python list s can only be multiplied by an integer, in which case the elements of the list are repeated. 
Broadcasting actually adds the matrix with the number.

#### Universal Functions

We will often need to transform data by applying a function to every element of an array.

Numpy has good support for these operations, called *universal functions* or ufuncs for short.

The
[numpy documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html?highlight=ufunc#available-ufuncs)
has a list of all available ufuncs.

>**Note**
>
>You should think of operations between a single number and an array, as we
just saw, as a ufunc.

Below, we will create an array that contains 10 points between 0 and 25.

In [117]:
# This is similar to range -- but spits out 10 evenly spaced points from 0.5 to 25.
x = np.linspace(0.5, 25, 10)
print(x)

[ 0.5         3.22222222  5.94444444  8.66666667 11.38888889 14.11111111
 16.83333333 19.55555556 22.27777778 25.        ]


We will experiment with some ufuncs below:

In [116]:
# Applies the sin function to each element of x
np.sin(x)

array([ 0.47942554, -0.08054223, -0.33229977,  0.68755122, -0.92364381,
        0.99966057, -0.9024271 ,  0.64879484, -0.28272056, -0.13235175])

You can use the inspector or the docstrings with `np.<TAB>` to see other available functions, such as

In [122]:
# Takes natural log of each element of x
np.uint8(x)


array([ 0,  3,  5,  8, 11, 14, 16, 19, 22, 25], dtype=uint8)

A benefit of using the numpy arrays is that numpy has succinct code for combining vectorized operations.

In [123]:
# Calculate log(z) * z elementwise
z = np.array([1,2,3])
np.log(z) * z

array([0.        , 1.38629436, 3.29583687])

**Exercise 7**

Recall from your courses that the equation for pricing a bond with coupon payment $ C $,
face value $ M $, yield to maturity $ i $, and periods to maturity
$ N $ is

$$
\begin{align*}
    P &= \left(\sum_{n=1}^N \frac{C}{(i+1)^n}\right) + \frac{M}{(1+i)^N} \\
      &= C \left(\frac{1 - (1+i)^{-N}}{i} \right) + M(1+i)^{-N}
\end{align*}
$$

In the code cell below, we have defined variables for `i`, `M` and `C`.

You have two tasks:

1. Define a numpy array `N` that contains all maturities between 1 and 10, including endpoints (*hint:* look at the `np.arange` function).  
1. Using the equation above, determine the bond prices of all maturity levels in your array.  

In [176]:
i = 0.03
M = 100
C = 5

# Define array here
#raise NotImplementedError()
N = np.arange(1,11)

# price bonds here

print(P)

[ 1  2  3  4  5  6  7  8  9 10]
