* python3 -m venv env
* source env/bin/activate
* pip install numpy pandas matplotlib seaborn scikit-learn

Kurulum için çalıştırılması gereken komutlar

In [2]:
t = (1,) # tuple
print(t)
print(type(t))
print(id(t))

(1,)
<class 'tuple'>
4565235744


In [3]:
x = [1,2] # list
print(x)
print(type(x))
print(id(x))

[1, 2]
<class 'list'>
4570515200


#### Exercise 1

Verify that tuples are indeed immutable and lists are not, by attempting the following:

- Changing the GDP in 2022 to 900
- Appending observations for 2018: a GDP of 779 and a population of 80
- Sorting the data ascending in years

In [4]:
# type(turks_data[1]) => tuple 

In [5]:
turks_data = [(2015, 11.06, 1.371), (2022, 1000, 1.364)]
###                 0                      1
###            0      1       2       0      1     2
turks_data[1]  = (2022, 900, 1.364)
print(turks_data)
x = (2018, 779, 80)
turks_data.append(x) 
print(turks_data)
sorted_turks = sorted(turks_data)
print(sorted_turks)

[(2015, 11.06, 1.371), (2022, 900, 1.364)]
[(2015, 11.06, 1.371), (2022, 900, 1.364), (2018, 779, 80)]
[(2015, 11.06, 1.371), (2018, 779, 80), (2022, 900, 1.364)]


# String Formatting

In [6]:
ulke = "Turkey" # String => Karakter Dizisi
# DRY  Dont Repeat Yourself
# WET  Write Everything Twice

ulke = "USA"
#       012
# "U" => karakter

```indisleme```

---------------------------------

In [7]:
liste = [[1,2,3],[4,5,6],[7,8,9]]
#           0       1       2
#         0 1 2   0 1 2   0 1 2
#          -3       -2       -1 
#        -3 -2 -1 
liste[0][1]

2

In [8]:
liste[-1] # [7,8,9]
liste[-1][-1] # 9

9

-----------------------------

In [9]:
sonuc = "Sayın ...... Hoş Geldiniz"
pi = 22/7

In [10]:
isim = "Anıl"
soyisim = "KAYA"
sonuc = f"Sayın {isim} {soyisim} Hoş Geldiniz {round(pi,2)}"
print(sonuc)

Sayın Anıl KAYA Hoş Geldiniz 3.14


In [11]:
sonuc = "Sayın {} {} {} Hoş Geldiniz".format(isim,soyisim,round(22/7,2))
print(sonuc)

Sayın Anıl KAYA 3.14 Hoş Geldiniz


In [12]:
sonuc = "Sayın %s  %s %2.2f Hoş Geldiniz" % (isim,soyisim,pi)
print(sonuc)

Sayın Anıl  KAYA 3.14 Hoş Geldiniz


In [13]:
# %pip install numpy

In [14]:
a = [1,2,3] # python list 
b = ["TR","EU","USA"]
c = ["1000000","50000","10000"]

for i in range(len(a)):
    metin = f"{i} indis numarasında  {a[i]} - X malının fiyatı {b[i]} ülkesinde {c[i]}" # str
    print(metin)

0 indis numarasında  1 - X malının fiyatı TR ülkesinde 1000000
1 indis numarasında  2 - X malının fiyatı EU ülkesinde 50000
2 indis numarasında  3 - X malının fiyatı USA ülkesinde 10000


In [15]:
for x,y,z in zip(a,b,c):
    metin = f"{x} - X malının fiyatı {y} ülkesinde {z}"
    print(metin)

1 - X malının fiyatı TR ülkesinde 1000000
2 - X malının fiyatı EU ülkesinde 50000
3 - X malının fiyatı USA ülkesinde 10000


In [16]:
print(*zip(a,b,c))

(1, 'TR', '1000000') (2, 'EU', '50000') (3, 'USA', '10000')


# Numpy

In [17]:
import numpy as np

In [18]:
x_3d_list = [
    [
        [1, 2, 3],
        [4, 5, 6]
        # 0 1  2 
        ], 
    [
        [10, 20, 30], 
        [40, 50, 60]
        ]
    ]
x_3d = np.array(x_3d_list)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [19]:
print(x_3d[0])
print(x_3d[1])

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [20]:
print(x_3d[0, 1, 1])

5


In [21]:
print(x_3d[0, :, :])

[[1 2 3]
 [4 5 6]]


In [28]:
liste = [1,2,3,4,5,6,7,8,9,10]
#         0 1 2 3 4 5 6 7 8 9
#       -10-9-8-7-6-5-4-3-2-1 
liste[1:3]
#        1 2
liste[-9:-7]


[2, 3]

In [29]:
liste[1:5:2] # 1,3

[2, 4]

In [30]:
liste[0:4]

[1, 2, 3, 4]

In [36]:
liste[::2]

[1, 3, 5, 7, 9]

In [37]:
liste[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [39]:
x_3d_list = [
    [
        [1, 2, 3], # 0
        [4, 5, 6] # 1
        # 0 1  2 
        ], 
    [
        [10, 20, 30], # 0  
        [40, 50, 60]  # 1
        ]
    ]
x_3d = np.array(x_3d_list)
print(x_3d[0, :, :])

[1 2 3]



What would you do to extract the array `[[4, 5], [40, 50]]` from `x_3d`?

In [60]:
print(x_3d[:,1,:2])

[[ 4  5]
 [40 50]]


In [59]:
liste = ["a","b","c","d","e","f","g"]
#         0   1   2   3   4   5   6
#         -7  -6  -5  -4  -3  -2  -1
# liste[3:6]   # 3 4 5
# liste[4:6]   # 4 5 

# liste[4:-1] # 4 5
# liste[-6:-3] # 1 2 3   => 1:4 <==>  -6:-3
liste[:4] # 0 1 2 3
liste[4:] # 4 5 6
liste[:] # 0 1 2 3 4 5 6

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [ ]:
x_3d_list = [   
    [  # 0
        [1, 2, 3], # 0
        [4, 5, 6] # 1
        # 0 1  2 
        ], 
    [  # 1
        [10, 20, 30], # 0  
        [40, 50, 60]  # 1
        ]
]
x_3d_list[1][0][1]

In [ ]:
x_3d_list = [   
    [  # 0
        [1, 2, 3], # 0
        [4, 5, 6] # 1
        # 0 1  2 
        ], 
    [  # 1
        [10, 20, 30], # 0  
        [40, 50, 60]  # 1
        ]
]
x_3d = np.array(x_3d_list)
print(x_3d[0, :, :]) # 2x2x3

In [65]:
x_3d.ndim,x_3d.shape,x_3d.size

(3, (2, 2, 3), 12)

In [68]:
sizes = (2, 3, 4) 
x = np.zeros(sizes) # note, a tuple!
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
x.ndim,x.shape,x.size

(3, (2, 3, 4), 24)

In [82]:
y = np.ones((2,4))
y

array([[0.00444444, 0.00444444, 0.00444444, 0.00444444, 0.00444444],
       [0.00444444, 0.00444444, 0.00444444, 0.00444444, 0.00444444],
       [0.00444444, 0.00444444, 0.00444444, 0.00444444, 0.00444444],
       [0.00444444, 0.00444444, 0.00444444, 0.00444444, 0.00444444],
       [0.00444444, 0.00444444, 0.00444444, 0.00444444, 0.00444444]])

In [74]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])